### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by fatinghenji** [AzirZhang/GenshinTeamDPSCalculator#1]
### 好处
- 用户可以在网页上填写角色的各种数据，包括武器、以及圣遗物
- 导出格式明确，参看[Genshin Open Object Description (GOOD)](https://frzyc.github.io/genshin-optimizer/#/doc)
  - 有人维护了个[国内版本](https://dualie.ink/genshin-optimizer)，但不经常同步上游
### 好处
- 降低用户使用困难程度
- 数据来源稳定可靠，减少因输入错误产生的计算偏差
   - [honeyhunterworld](https://genshin.honeyhunterworld.com/db/enemy/?lang=CHS)
   - [Genshin Impact Wiki-Resistance](https://genshin-impact.fandom.com/wiki/Resistance)

**Comment by ChenZhang-2000** [comment]
感谢您的建议

首先，这个项目的目标在于理论计算大量配队的伤害，从而筛选出合适的配队。在这个需求下，一个角色可能有多个版本（在我枚举优菈雷神配队的时候，碰到了六种不同配装下的北斗和四种不同配装下的神里）
同时，我查看了一下GO格式的数据，发现这个数据格式似乎需求一个原神整体角色、机制、技能、圣遗物、和武器的数据库。
比如，圣遗物的形式较难满足上文中所提的”一个角色多种配装“的情况，因为手动输入的话可以直接输入目标面板，而圣遗物形式则需要对角色、圣遗物、技能都进行标注诸如”哪一段技能是什么类型，圣遗物的buff作用于什么，什么情况下触发，触发哪些buff“。这个难度可以说已经近乎是一个原神模拟器了。

另外，关于怪物数据本地化选择上，我正在考虑这个事项，会在软件基础公能稳定之后添加
